Traceback (most recent call last):
  File "/home/bb1000/miniconda3/envs/bb1000/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/bb1000/miniconda3/envs/bb1000/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/bb1000/miniconda3/envs/bb1000/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/bb1000/miniconda3/envs/bb1000/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/bb1000/miniconda3/envs/bb1000/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/bb1000/miniconda3/envs/bb1000/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/bb1000/miniconda3/envs/bb1000/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/bb1000/miniconda3/envs/bb1000/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# %load stocks.py
import csv
import sys
import pathlib

this_code = sys.argv[0]

if len(sys.argv) < 2:
    print(f"Usage: {this_code} csv_file")
    exit()

csv_file = sys.argv[1]

if not pathlib.Path(csv_file).is_file():
    print(f'{csv_file} does not exist')
    exit()
    
csv_reader = csv.DictReader(open(csv_file))
shares = 0
for row in csv_reader:
    # convert the price data from string to float skipping the initial $ character (using [1:])
    closing_price_of_day = float(row['Close/Last'][1:])  
    if shares == 0:
        latest_price = closing_price_of_day # save the latest price from the first iteration
    shares_purchased = 1/closing_price_of_day
    shares += shares_purchased
    # print(shares_purchased, shares)

value = shares * latest_price
print(f'Total ({csv_file}) shares={round(shares, 3)} value={round(value, 2)}')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[1], line 18[0m
[1;32m     15[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mcsv_file[38;5;132;01m}[39;00m[38;5;124m does not exist[39m[38;5;124m'[39m)
[1;32m     16[0m     exit()
[0;32m---> 18[0m csv_reader [38;5;241m=[39m csv[38;5;241m.[39mDictReader([38;5;28;43mopen[39;49m[43m([49m[43mcsv_file[49m[43m)[49m)
[1;32m     19[0m shares [38;5;241m=[39m [38;5;241m0[39m
[1;32m     20[0m [38;5;28;01mfor[39;00m row [38;5;129;01min[39;00m csv_reader:
[1;32m     21[0m     [38;5;66;03m# convert the price data from string to float skipping the initial $ character (using [1:])[39;00m

File [0;32m~/miniconda3/envs/bb1000/lib/python3.10/site-packages/IPython/core/interactiveshell.py:282[0m, in [0;36m_modified_open[0;34m(file, *args, **kwargs)[0m
[1;32m    275[0m [38;5;28;01mif[39;00m file [38;5;129;01min[39;00m {[38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m}:
[1;32m    276[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    277[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mIPython won[39m[38;5;124m'[39m[38;5;124mt let you open fd=[39m[38;5;132;01m{[39;00mfile[38;5;132;01m}[39;00m[38;5;124m by default [39m[38;5;124m"[39m
[1;32m    278[0m         [38;5;124m"[39m[38;5;124mas it is likely to crash IPython. If you know what you are doing, [39m[38;5;124m"[39m
[1;32m    279[0m         [38;5;124m"[39m[38;5;124myou can use builtins[39m[38;5;124m'[39m[38;5;124m open.[39m[38;5;124m"[39m
[1;32m    280[0m     )
[0;32m--> 282[0m [38;5;28;01mreturn[39;00m [43mio_open[49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '-f'
FileNotFoundError: [Errno 2] No such file or directory: '-f'

